[project]
name = "my-project"
version = "0.1.0"
description = "A short description of your project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # "pandas>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    # "pytest>=8.0.0",
]